export const TestCourses = [
  {
    id: 'one',
    title: 'Nhập môn trí tuệ nhân tạo',
    image: require('../../assets/images/course_ai.png'),
    rate: '5',
    price: '799000',
    videoDemoId: 'mfNWxURTJEA',
  },
  {
    id: 'two',
    title: 'Giao tiếp tiếng Anh chuyên nghiệp cho người làm kinh doanh',
    image: require('../../assets/images/course2.png'),
    rate: '1.5',
    price: '799000',
    videoDemoId: 'mfNWxURTJEA',
  },
  {
    id: 'three',
    title: 'Sơ đồ tư duy',
    image: require('../../assets/images/course1.png'),
    rate: '2',
    price: '799000',
    videoDemoId: 'mfNWxURTJEA',
  },
  {
    id: 'four',
    title: 'Giao tiếp tiếng Anh chuyên nghiệp cho người làm kinh doanh',
    image: require('../../assets/images/course2.png'),
    rate: '2.5',
    price: '799000',
    videoDemoId: 'mfNWxURTJEA',
  },
  {
    id: 'five',
    title: 'Sơ đồ tư duy',
    image: require('../../assets/images/course1.png'),
    rate: '3',
    price: '799000',
    videoDemoId: 'mfNWxURTJEA',
  },
  {
    id: 'six',
    title: 'Giao tiếp tiếng Anh chuyên nghiệp cho người làm kinh doanh',
    image: require('../../assets/images/course2.png'),
    rate: '3.5',
    price: '799000',
    videoDemoId: 'mfNWxURTJEA',
  },
];
